### PR TITLE
Datepicker and human-readable date formatting in ticket creation form. Closes #69

### LINKED ISSUE #69: Date/Time repeatedly strtotime()'d in view
The culprit is [this code](https://github.com/AbuseIO/AbuseIO/blob/master/app/Http/Requests/TicketFormRequest.php#L75):

```php
    if (strtotime($input['timestamp']) !== false) {
        $input['timestamp'] = strtotime($input['timestamp']);
    }

```

So the solution that involves the least amount of changing things is to solve the above which I've done, and then in the view we convert the timestamp field to a string with `date('Y-m-d H:i:s')`. This is the path of least friction that I can see. But also there's a little problem there. Laravel Form Builder has a set order of preference when considering what value to put in a field even when we specify what we want. It will look to old input first, and then consider the one we've provided. We want to override what's in the old input. A hack would be to create a helper function that simply overrides the old input, but I don't think we want hacks in the codebase?

So for now I'm engaging the maintainers of the Form Builder package to see if they can consider and accept my PR which enables us (as an option) to tell the Form Builder to use the value provided if we want that, and not to look for old input.

Whatever the end result will be, soon as we have this fixed I'll drop in the datepicker

### PR DESCRIPTION
**Pull request by ihatehandles**
This address issue #69 in a much cleaner way. I thought it'd be too much of a breaking change at this point to change the schema so this lets the backend deal with its regular timestamp format and in the form we simply display the date in a more readable way with the `date()` function.

Also implemented the timepicker.

What I did not like though is that I added the datepicker stylesheet link tag in the `extrajs` section which adds it to the footer. The `app.blade` doesn't have an `extracss/extraheaders` section. So I don't know if we should have one or not (up to you), or if you're happy having the stylesheet linked in the footer.

If this PR sits well with you I can move on to have the datepicker on every form input that requires a date.

### CODE REVIEW

**Comment by marknl** [comment]
Great PR! We will merge this into 4.1

**Comment by marknl** [comment]
Thanks mate, we've included this in our next release. 
I've had to port in manually, since we cannot move PR's from master to another branch.

**Comment by ihatehandles** [comment]
Pleasure. Has the sprint to the next release started?

**Comment by marknl** [comment]
We're having a meeting the 9th of April. Then we will define what will be in 4.1.

**Comment by ihatehandles** [comment]
Sounds good.

**Pull request closed without merging**
