### PR TITLE
perform easier isValidRegex-checks

### PR DESCRIPTION
**Pull request by imme-emosol**

### CODE REVIEW

**Comment by kruisdraad** [comment]
I dont see the improvement, performance wise its the same but perhaps the output less reliable due to added conditions to be matched in the return?

@marknl what do you think

**Comment by imme-emosol** [comment]
The improvement is that those extra checks were in other places in some codebases before, so I moved them here. Because I prefer for those places to just read ``isValidRegex($something);``. Whether it's a improvement for performance or something, I do not know. That probably depends on whether ``preg_match`` does or does not check for ``null`` or non-``string``-input, in all used versions of php. So it's more of an improvement regarding the readability of code in other areas of the codebase, adding some checks to prevent ``E_NOTICE``-warnings when providing 'wrong" input in some stricter debug-modus.

**Comment by marknl** [comment]
There is no improvement performance wise. In can see the improvement readability.

I'd rather say the extra checks are redundant. We're only interested in preg_match's ability to execute the input as a regex, there's no need for extra validations.

I agree there should be one check like this that can be re-used, but there's no need to add all other methods to that check too, since the current one is already good. Leaving this function for what it is, and replacing the other checks with this one would be i.m.o. the best course of action.

**Comment by imme-emosol** [comment]
Sure, inputs where ``$regex = null;`` or ``$regex = 8;`` will probably be minimal .. and where they are made, the ones who make them can put in some effort to look for the issue (since the php-warning's are @-silenced).

**Pull request closed without merging**
