### PR TITLE
Add Apple Filing Protocol Report

### PR DESCRIPTION
**Pull request by yakatz**

### CODE REVIEW

**Comment by kruisdraad** [comment]
Thank you for your work.

this change looks good and once completed unit tests will be accepted.

**Comment by yakatz** [comment]
Added test

**Comment by kruisdraad** [comment]
failed unit test on sample:

pushing extra/notifier-samples/shadowserver/2019-01-06-scan_afp-sample-ip.csv.zip.eml into queue
                                                                                     
  [Swift_TransportException]                                                         
  Connection could not be established with host localhost [Connection refused #111]

**Comment by yakatz** [comment]
Fixed in https://github.com/AbuseIO/parser-shadowserver/pull/2/commits/988fde7ec20ea7b963f11d807e31baec81886842

**Comment by kruisdraad** [comment]
still errors:

pushing extra/notifier-samples/shadowserver/2019-01-06-scan_afp-sample-ip.csv.zip.eml into queue
                                                                                     
  [Swift_TransportException]                                                         
  Connection could not be established with host localhost [Connection refused #111]

**Comment by yakatz** [comment]
I think the automated test can't work until https://github.com/AbuseIO/parser-shadowserver/pull/2 is merged and a new release is put out and then `composer update abuseio/parser-shadowserver` is run and committed. Otherwise there is no way for travis-ci to load that new code.

**Pull request merged**
