### PR TITLE
Support sending AdminAlert'ed attachments in zip format

### PR DESCRIPTION
**Pull request by miff2000**
I've seen that some mail systems (Microsoft 365, for one) seem to truncate the attachments on emails that get bounded to admins. These are the emails which AbuseIO has not been able to parse, and so it send to be triaged manually.

I've therefore added support for bundling attachments in a `.zip` file instead of attaching them as-is to the bounce email. From my testing, this stops the attachments from getting truncated.

I've added the new config option `app.attachment_format` (`APP_ATTACHMENT_FORMAT` environment variable) to enable overriding the default (I've named `multifile`) with the new option `zipfile`).

If no config changes are made, things carry on as-is. If `attachment_format` is changed to `zipfile`, it will create a `.zip` in `/tmp`, add all attachments into it, then send that to the admin instead.

### CODE REVIEW

**Comment by miff2000** [comment]
I've based this on the `4.1` branch as it's the latest production build and it's the version I run.

Let me know if this is incorrect.

**Comment by kruisdraad** [comment]
4.3.1 is the latest version.
also this code contains breaking changes and must be investigated before mainstreamed

**Comment by miff2000** [comment]
> 4.3.1 is the latest version.

Ah okay. Shall I rebase onto and fix any conflicts with that branch then?

**Comment by miff2000** [comment]
How can I progress this issue? Shall I rebase onto `master`?

**Comment by miff2000** [comment]
@kruisdraad, please can you let me know how I can get this approved and merged in? I think it's a worthwhile feature to have and shouldn't break any existing functionality.

If there are any changes you need making, just let me know. I based it off the `4.1` branch as I [couldn't see any updated docs past 4.1](https://github.com/AbuseIO/abuseio-docs/branches)

**Comment by kruisdraad** [comment]
master = 4.3.1
the build failed, also putting it into a ZIP is a breaking change as the output format is change and some systems ingest EML. Sadly i did not had the time to look into this.

**Comment by kruisdraad** [comment]
a new PR against master must be made, this will break the old branch

**Comment by miff2000** [comment]
> a new PR against master must be made, this will break the old branch

Yeah, I had rebased on origin/master, but realised I have my repo as the origin, not yours. I'm going to rebase on `upstream/master` (your repo) instead. There's only 1 actual commit

**Comment by miff2000** [comment]
Closing this in favour of #384

**Pull request closed without merging**
