### PR TITLE
Solved parsing error

### PR DESCRIPTION
**Pull request by jviersel**

### CODE REVIEW

**Comment by kruisdraad** [comment]
can you please provide the parse error info as well. The edit looks good, but this has worked in the past.

**Comment by kruisdraad** [comment]
also looking at master, this also seems to be there (line 60) with added code. did you pull first?

**Comment by pettai** [comment]
> can you please provide the parse error info as well. The edit looks good, but this has worked in the past.

See https://github.com/AbuseIO/AbuseIO/issues/344

**Comment by pettai** [comment]
> also looking at master, this also seems to be there (line 60) with added code. did you pull first?

https://github.com/AbuseIO/AbuseIO/blob/master/app/Http/Controllers/NetblocksController.php#L60

it doesn't AFAICT

**Pull request merged**
