### PR TITLE
added classifications for new shadowserver feeds. Also fixed IPMI typo

### PR DESCRIPTION
**Pull request by iTeV**
Related PR in parser-shadowserver repo: https://github.com/AbuseIO/parser-shadowserver/pull/8

### CODE REVIEW

**Comment by kruisdraad** [comment]
Typo's cannot be fixed, because they are still linked to old reports. You will need to keep the original (wrong) definition and the new one. There is no alias method yet, which would be a cool way to fix typo's like this. Also it seems your original branch is out of data, making it impossible to run CI

**Comment by iTeV** [comment]
Ah, yeah. I see now. I'll fix the outdated branch and i'll make sure to revert the IPMI commit!

**Comment by kruisdraad** [comment]
looks good, lets wait on CI to complete and then i can merge the PR

**Comment by iTeV** [comment]
JFYI: Some of the CI pipelines seem to be broken. The other PR from june this year (https://github.com/AbuseIO/AbuseIO/pull/385) still has some "busy" CI pipelines aswell :)

**Pull request merged**
