### PR TITLE
 	Grammar, typos and formatting touches

### PR DESCRIPTION
**Pull request by ihatehandles**
Changes to docs in master

### CODE REVIEW

**Comment by marknl** [comment]
Thank you for these changes. Tomorrow we will be launching 4.0.0

**Comment by ihatehandles** [comment]
That's good to hear! I hope to contribute to the code soon when I have a better grasp of everything. The installation.md for v4 also has a few typos needing correction. Do I make them today or after the launch?

**Comment by kruisdraad** [comment]
Whenever you want, today would be fine.

Also if you like we have ASH templates in :
https://github.com/AbuseIO/AbuseIO/tree/master/resources/lang

That would love some attention too :)

Thank you for your help!

**Comment by ihatehandles** [comment]
No, thank you! Looking to learn about networking from AbuseIO. So the docs are a good start for me to be forced to lookup what certain things mean ;)

The changes in this PR are for the rest of the files (configuration-main.md, data_collection.md, migration.md, notifications.md) besides installation.md which Ill also do. So feel free to merge this one as well.

Hadn't noticed the ASH templates, will get on that as well (the EN ones of course)

**Comment by ihatehandles** [comment]
@kruisdraad Ignore this PR. I don't like the dirty merges that snuck in. Bringing them in in a clean one, all the edits to master combined.

**Pull request closed without merging**
